###################################################################################################################################################
##                                           This plugin made by Altkat(StreetMelodeez) V1.0                                                     ##
##                                   Feel free to contact me for anything on discord: streetmelodeez                                             ##
##              Please use /aa reload to reload the plugin, or restart the server after you changed something in the config file.                ##
###################################################################################################################################################
bstats: true # Should the plugin send data to bStats?

# you can use placeholders from PlaceholderAPI in the messages. like %player_name%
# use | to print on a new line
presets: # you can add as many presets as you want
  preset1: "&aThis is &6my cool| &amessage wow!"
  store-preset: "&6You can get ranks|&6on our store &b/store"
  discord-preset: "&9Join our discord server|&bdiscord.gg/yourdc"
  greeting: "&eHello &a%player_name%|&eHow is it going?"


auto-announce:
  enabled: false    # should the plugin announce messages automatically
  interval: 30      # in seconds
  mode: "ORDERED"   # ORDERED, RANDOM
  messages:         # you can add as many messages as you want
    custommessage1:
      message: "&eHello &a%player_name%|&eHow is it going?"
      style: "GOAL"   # GOAL, TASK, CHALLENGE
      icon: "EMERALD" # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    custommessage2:
      message: "&9Join our discord server|&bdiscord.gg/yourdc"
      style: "TASK"
      icon: "DIAMOND"
    vipmessage:
      message: "&6You can get ranks|&6on our store &b/store"
      style: "CHALLENGE"
      icon: "GOLD_INGOT"
